import React from "react";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home(serverSideProps) {
  const ms =
    typeof window !== "undefined"
      ? location.search.substring("?ms=".length)
      : serverSideProps && serverSideProps.ms
      ? serverSideProps.ms
      : useRouter().query.ms;

  const now = ms ? Date.now() - parseInt(ms || 0, 10) : "-";
  var [old, setOld] = React.useState(
    typeof window === "undefined"
      ? now
      : parseInt(document.querySelector("#old").textContent, 10)
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 id="title" className={styles.title}>
          Total: <span id="old">{now}</span>ms
        </h1>

        <h1 id="server" className={styles.title}>
          Server: {old || "N/A"}ms
        </h1>
      </main>
    </div>
  );
}
